# Prevent Aider from stamping commits with the Co-Authored-By stuff for the
# model used.
attribute-co-authored-by: false
attribute-commit-message-author: false
attribute-commit-message-committer: false
# This prevents Aider from prompting to add itself to the .gitignore file.  If
# you're using Aider, you should add Aider's settings to your global gitignore
# file instead of polluting every repository you touch, just like you should do
# with your editor settings and temporary files.
gitignore: false
read:
  - rustfmt.toml
  - llms.org
  - src
